// eslint-disable-next-line no-shadow
export enum ApiRouteKey {
  Group = "Group",
  Bush = "Bush",
  User = "User",
  TaskPerformer = "TaskPerformer",
  Manager = "Manager",
  PetrolStation = "PetrolStation",
  Category = "Category",
  Attachment = "Attachment",
  Comment = "Comment",
  Priority = "Priority",
  StatusHistory = "StatusHistory",
  Status = "Status",
  TagWord = "TagWord",
  Ticket = "Ticket",
}

export const APIRoute = {
  [ApiRouteKey.Group]: {
    All: "/group",
    Info: (id: string) => `/group/${id}`,
    Create: undefined,
    Update: undefined,
    Delete: undefined,
  },
  [ApiRouteKey.Category]: {
    All: "/category",
    Info: (id: string) => `/category/${id}`,
    Create: undefined,
    Update: undefined,
    Delete: undefined,
  },
  [ApiRouteKey.Bush]: {
    All: "/bush",
    Info: (id: string) => `/bush/${id}`,
    Create: undefined,
    Update: undefined,
    Delete: undefined,
  },
  [ApiRouteKey.User]: {
    All: "/user",
    Info: (id: string) => `/user/${id}`,
    Create: "/user",
    Update: (id: string) => `/user/${id}`,
    Delete: (id: string) => `/user/${id}`,
  },
  [ApiRouteKey.TaskPerformer]: {
    All: "/task-performer",
    Info: (id: string) => `/task-performer/${id}`,
    Create: "/task-performer",
    Update: (id: string) => `/task-performer/${id}`,
    Delete: (id: string) => `/task-performer/${id}`,
  },
  [ApiRouteKey.Manager]: {
    All: "/manager",
    Info: (id: string) => `/manager/${id}`,
    Create: "/manager",
    Update: (id: string) => `/manager/${id}`,
    Delete: (id: string) => `/manager/${id}`,
  },
  [ApiRouteKey.PetrolStation]: {
    All: "/petrol-station",
    Info: (id: string) => `/petrol-station/${id}`,
    Create: "/petrol-station",
    Update: (id: string) => `/petrol-station/${id}`,
    Delete: (id: string) => `/petrol-station/${id}`,
  },
  [ApiRouteKey.Attachment]: {
    All: "/attachment",
    Info: (id: string) => `/attachment/${id}`,
    Create: "/attachment",
    Update: (id: string) => `/attachment/${id}`,
    Delete: (id: string) => `/attachment/${id}`,
  },
  [ApiRouteKey.Comment]: {
    All: "/comment",
    Info: (id: string) => `/comment/${id}`,
    Create: "/comment",
    Update: (id: string) => `/comment/${id}`,
    Delete: (id: string) => `/comment/${id}`,
  },
  [ApiRouteKey.Priority]: {
    All: "/priority",
    Info: (id: string) => `/priority/${id}`,
    Create: "/priority",
    Update: (id: string) => `/priority/${id}`,
    Delete: (id: string) => `/priority/${id}`,
  },
  [ApiRouteKey.StatusHistory]: {
    All: "/status-history",
    Info: (id: string) => `/status-history/${id}`,
    Create: "/status-history",
    Update: (id: string) => `/status-history/${id}`,
    Delete: (id: string) => `/status-history/${id}`,
  },
  [ApiRouteKey.Status]: {
    All: "/status",
    Info: (id: string) => `/status/${id}`,
    Create: "/status",
    Update: (id: string) => `/status/${id}`,
    Delete: (id: string) => `/status/${id}`,
  },
  [ApiRouteKey.TagWord]: {
    All: "/tag-word",
    Info: (id: string) => `/tag-word/${id}`,
    Create: "/tag-word",
    Update: (id: string) => `/tag-word/${id}`,
    Delete: (id: string) => `/tag-word/${id}`,
  },
  [ApiRouteKey.Ticket]: {
    All: "/ticket",
    Info: (id: string) => `/ticket/${id}`,
    Create: "/ticket",
    Update: (id: string) => `/ticket/${id}`,
    Delete: (id: string) => `/ticket/${id}`,
  },
} as const;

export const REQUEST_TIMEOUT = 30 * 1000;
